9a)


#include <iostream>
#include <string>
using namespace std;

class CustomException {
public:
    string message;
    CustomException(string msg) : message(msg) {}
};
int main() {
    try {
        int choice;
        cout << "Enter a number (1-3) to trigger different exceptions: ";
        cin >> choice;

        if (choice == 1) {
            throw 42;
        } else if (choice == 2) {
            throw 3.14;
        } else if (choice == 3) {
            throw CustomException("Custom exception triggered!");
        } else {
            throw "Unknown exception";
        }
    }
    catch (int e) {
        cout << "Caught an integer exception: " << e << endl;
    }
    catch (double e) {
        cout << "Caught a double exception: " << e << endl;
    }
    catch (CustomException e) {
        cout << "Caught a custom exception: " << e.message << endl;
    }
    catch (...) {
        cout << "Caught an unknown exception!" << endl;
    }

    return 0;
}






9b)

#include <iostream>
using namespace std;
class Employee {
public:
    virtual void showRole() = 0;
};
class Manager : public Employee {
public:
    void showRole() override {
        cout << "I am a Manager. I manage teams." << endl;
    }
};
class Developer : public Employee {
public:
    void showRole() override {
        cout << "I am a Developer. I write code." << endl;
    }
};
int main() {
    Employee* employees[2];
    Manager m;
    Developer d;
    employees[0] = &m;
    employees[1] = &d;

    for (int i = 0; i < 2; ++i) {
        employees[i]->showRole();
    }

    return 0;
}

